# -*- coding: utf-8 -*-
"""00_Hola_mundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16k77m_90Kt3QxW9AeT-u51bj1tzwhw-u

<h1><b>Primer programa</b></h1>

---


<p>esto es un texto de introduccion<p>
"""

print("Hola mundo")
print("primeramente podemos ver que no necesitamos declarar variables")
numero1=int(input("ingrese un numero: "))
numero2=int(input("ingresa otro numero: "))
suma=numero1+numero2
print(f"la suma es: {suma}")

print("Tambien puedes cambiar el valor de las variables muy dratiscamente")
suma = "este es un cambio drastico"
print(f"ahora ya no es un numero, ahora es un texto: {suma")

print("Bienvenido usuario")
print("ingresar un maximo de 10 calificaciones ")
num1=int(input("ingresar primera calificacion: "))
num2=int(input("ingresar segunda calificacion: "))
num3=int(input("ingresar la tercera calificacion: "))
num4=int(input("ingresar la cuarta calificacion: "))
num5=int(input("ingresar la quinta calificacion: "))
num6=int(input("ingresar la sexta calificacion: "))
num7=int(input("ingresar la septima calificacion: "))
num8=int(input("ingresar la octava calificacion: "))
num9=int(input("ingresar la novena calificacion: "))
num10=int(input("ingresar la decima calificacion: "))
suma = num1+num2+num3+num3+num4+num5+num6+num7+num8+num9+num10
promedio = suma / 10
print(f"el promedio total es igual a: {promedio}")