# -*- coding: utf-8 -*-
"""03 Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15r8OP81FaFnkXxkI6sLvfZij0MKHLxZ4

# String
Son el tipo de dao que incluye textos. Cualquier informacion escrita como un texto es considerado como un "string"
"""

letra = 'p'                    #una sola letra puede considerarse un string
print(letra)                   
print(len(letra))              #podemos calcular 
saludo = 'hello world!'        #un string puede ser una palabra
print(saludo)                  #hello world
print(len(saludo))             #13
oracion = "hope you ae enjoying 30 days of python challenge"
print(oracion)
print(len(oracion))

"""Tambien podemos crear strings multilineas haciendo uso de tres comillas simples(") o tres pares de comillas dobles"""

multiline_string = '''Pac man originalmente se llamaba puck man.
lo cambiaron no porque  pac - man fuera redondo.
paku paku significa abrir y cerrar la boca y tuvieron miedo de que la gente tachara la 'p' y
la convirtiera en 'f''''
print(multiline_string)

"""# **Secuencias de escape**

*  \n. Linea nueva
*  \t:Tabulacion(8 espacios)
*  \back slash 
*  ':single quote(')
*  ":Double quote(")
"""

print('Este es un ejemplo de salto de linea .\¿lo notas?') # line break
print('dia\tTemas\tEjersicios') #agregando una tabulacion
print('dia 1\t3\5')
print('dia 2\t3\t5')
print('dia 3\t3\t5')
print('dia 4\t3\t5')
print('este es un simbolo backslash (\\)') # para escribir un backslash
print('in every programming language it starts with \"hello, world\"'') #para escribir comillas dentro de las comillas

"""# String con variables"""

name, surname, alias, age = "erick", "borges", "alecs". 23

print("me llamo:", name , surname)
print("mi edad es:", age,  ", mis amigos me dicen:". alias)

print("mi nombre es {} {} y mi edad es {}".format (name, surname, age))
print("mi nombre es %s %s y mi edad es %d" %(name, surname, age))
print(f"mi nombre es {name} {surname} y mi edad es {age}") #esta es la mejor, la mas aceptada

"""# Strings como secuencia de caracters
los strings son secuencias de letras unidas que forman palabras. tenemos distintas maneras de descomponer un string en cada una de sus unidades. sin embargo la manera mas simple de extraer cada miembro de un string es desempaqutarlo en distintas variables
"""

lenguaje = a,b,c,d,f,
#lenguaje =str(lenguaje)
a,b,c,f,e,f = lenguaje
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

lenguaje = 123456
print(type(lenguaje))
lenguaje=str(lenguaje)
print(type(lenguaje)
a,b,c,d,e,f = lenguaje

)

lenguaje = "python"
a,b,c,d,e,f = lenguaje
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

primer_letra = lenguaje[0]
segunda_letra = lenguaje[1]
tercer_letra = lenguaje[2]
print(primer_letra)
print(segunda_letra)
print(tercer_letra)

"""#Recortando strings
*   Elemento de lista
*   Elemento de lista


"""

lenguaje = 'python'
primeros_tres = lenguaje[0:3] #starts at zero index and up to 3 but not include 3
print(primeros_tres) #Pyt

ultimos_tres = lenguaje[3:6]
print(ultimos_tres) #hon

#otra forma Python
ultimos_tres = lenguaje[-3:]
print(ultimos_tres) #hon
primeros_tres = lenguaje[:-3]
print(primeros_tres) #hon

"""# Invirtiendo strings"""

saludo = 'hello, world!'
print(saludo[::-1])

"""# Saltando letras"""

lenguaje = 'python'
new = lenguaje[0:6:2]
print(new)

"""Metodos con strings

# Convertir la primera leta en mayuscula
"""

text = 'aprendiendo'+'python'+'en'+'clase'
print(type(text))
text = 'aprendiendo python en clase'
print(type(text))
print(text.capitalize())

"""# Contar las veces que se reputa un caracter"""

text = 'aprendiendo python en clase'
print(text.count('a'))
print(text.count('y', 7, 14))
print(text.count('en'))

"""# regresa la posicion donde se encuentra el caracter
si no se encuentra regresa -1
"""

text = 'aprendiendo python en clase'
print(text.find('y'))
print(text.find('th'))
print(text.find('am'))

"""Actividad
Gnera palindormos y compruebas que efectivamente lo son


"""



text

