# -*- coding: utf-8 -*-
"""04 listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LluI8FfRt2XI1HQwe-uG02XaRNy1DdJ0

Una **lista** es una coleccion de diferentes tipos de datos que tienen un orden modificable. Una lista puede estar vacia o contener distintos tipos de items.
Si esta difinicion no les suena o les parece un poco complicada, tal vez seria mas facil compararlas con lo que anteriormente vimos como **Array**
"""

my_list = list() #primera forma de declarar una lista
other_list = [] #segunda forma de declarar una lista
print(len(my_list))
print(len(other_list))

my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))
print(len(my_list))
print(my_list[0])

other_list = [1,2.5, 3, 'erick', 'borges']
print(other_list)
print(type(other_list))

print(other_list[0])
print(other_list[-1])

"""# Contar componentes en una lista"""

print(other_list.count("borges"))

"""# Agregar componentes a una lista"""

frutas = ['banana', 'naranja', 'mango', 'limon' ]
print(frutas)
frutas.append('manzana')
print(frutas)
frutas.append('aguacate')
print(frutas)

"""Insertar componenetes a una lista"""

frutas = ['banana', 'naranaja', 'mango', 'limon' ]
print(frutas)
frutas.insert(2, 'manzana')
print(frutas)
frutas.insert(3, 'aguacate')
print(frutas)

"""# Revomer componentes de una lista """

frutas = ['banana', 'naranja', 'mango', 'limon', 'manzana', 'aguacate' ]
print(frutas)
frutas.remove('manzana')
print(frutas)
frutas.remove('aguacate')
print(frutas)
frutas.remove(frutas[0])
print(frutas)

"""# Unir listas"""

positivos = [1, 2, 3, 4]
cero = [0]
negativos = [-1, -2, -3, -4]

enteros = negativos + cero + positivos

print(enteros)
print(len(enteros))