# -*- coding: utf-8 -*-
"""06_sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BmLaF4DmujsoWzcY1rZTChtbpnk1QoM2

# Sets

Es una colección de elementos. La definición matemática de un conjunto es una colección de elementos distintos desordenados y no indexados.

En Python, el conjunto se usa para almacenar elementos únicos, y es posible encontrar la unión, la intersección, la diferencia, la diferencia simétrica, el subconjunto, el superconjunto y el conjunto disjunto entre conjuntos.
"""

my_set = set()
other_set = {}
print(type(my_set))
print(type(other_set))

other_set = {1, 2.5,3, 'Erick', 'borges', 'aguilar', 'morales', 'Borges'}
print(type(other_set))

other_set = {}
print(type(my_set))
print(type(other_set))

#ejemplo de conjunto
fruits = {'banana', 'mango', 'naranja', 'limon'}

"""# Obtener la longitud del conjunto"""

my_set={'banana', 'mango', 'naranja', 'limon'}
print(len(my_set))

"""Para verificar si existe un elemento en una lista, usamos in operador de membresía."""

frutas = {'banana', 'mango', 'naranja', 'limon'}
print('mango' in frutas) # True

"""# Agregar items"""

print(my_set)
my_set.add('manzana')
print(my_set)

"""# Agregar multiples items"""

print(my_set)
vegetales = {'tomate', 'papa', 'zanahoria'}
print(vegetales)
my_set.update(vegetales)
print(my_set)

"""# Remover objetos"""

frutas = {'banana', 'mango', 'naranja', 'limon'}
frutas.pop()  # remueve un objeto aleatorio del set

numeros = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
numeros_par ={2, 4, 6, 8, 10, 12, 14}
print(numeros.intersection(numeros_par))