# -*- coding: utf-8 -*-
"""07_diccionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_n-9gJqDkHkN5TnCFnNc_OGIRah-XFo

# Diccionario
es una coleccion deshornedana, modificables y emparejados
"""

my_dict = dict()
other_dict = {}
print(type(my_dict))
print(type(other_dict))

"""una de las caracteristicas mas importantes de los diccionarios es que estan **emparejados**, lo cual significa que siempre se van a componer de una **llave** y un **valor**

Key:value
"""

person = {
    'name': 'erick',
    'last_name': 'borges',
    'age': 23,
    'skills': ['javascript', 'react', 'python', 'swift'],
    'address': {
        'street': 'fco. I Madero',
        'telefono': 782123456
    }
}
print(person)

#Calcular longitud del diccionario
print(len(person))

"""# Acceder a los elementos"""

print(person['name'])
print(type(person['name']))

print(person['last_name'])
print(type(person['last_name']))

print(person['skills'])
print(type(person['skills']))

print(person['address'])
print(type(person['address']))

#Acceder a un elemento por nombre de clave genera un error si la clave no existe.
print(person.get('firs_name'))
print(person.get('country'))
print(person.get('skills'))
print(person.get('city'))

"""# Agregar nuevos campos"""

print(person)
person['country'] = 'poza rica'
print(person)

"""# Modificar campos"""

print(person)
person['last_name'] = 'galindo'
print(person)

"""# Verificar llaves"""

print('name' in person)
print('marital_status' in person)

"""# Analizar todas las llaves"""

print(person.keys())

"""# Analizar todos los valores existentes"""

print(person.values())