# -*- coding: utf-8 -*-
"""08_condicionales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYaypmyKrBlsAn3c5rM0FNK67dt2Rq1x

# Condicionales
De forma predeterminada, las declaraciones en el script de Python se ejecutan secuencialmente de arriba a abajo. Si la lógica de procesamiento lo requiere, el flujo secuencial de ejecución se puede alterar de dos formas:

**Ejecución condicional:** se ejecutará un bloque de una o más sentencias si cierta expresión es verdadera

**Ejecución repetitiva:** un bloque de una o más sentencias se ejecutará de forma repetitiva siempre que cierta expresión sea verdadera. En esta sección, cubriremos las declaraciones if, else y elif. Los operadores lógicos y de comparación que aprendimos en las secciones anteriores serán útiles aquí.

# Condicional if
En python y otros lenguajes de programación, la palabra clave if se usa para verificar si una condición es verdadera y ejecutar el código de bloque. Recuerde la sangría después de los dos puntos.
"""

#Sintaxis
if condition:
  aqui pones lo que se te ocurra  si se cumple
  else:
    aqui: pones lo que se te ocurra si no se cumple

numero=int(input("ingresa un numero: "))
if numero < 0:
  print('el numero es negativo')
else:
    print('el numero es positivo')

"""# IF else
lo utilizaremos para tomar desiciones basandonos en multiples *condicionales*
Si la condición es verdadera, se ejecutará el primer bloque, si no, se ejecutará la otra condición.
"""

#Ejemplo if else donde al no cumplirse la condicion if pasa a else en automatico
a = 3
if a < 0:
    print('a es un numero negativo')
else:
    print('a es un numero positivo')

"""# IF ELIF"""

#Ejemplo con variables
numero=int(input("ingrese un numero:"))
if numero < 0:
  print('el numero es negativo')
elif numero > 0:
  print('el numero es positivo')

"""# IF ELIF ELSE
Lo utilizaremos para  tomar desiciones basandonos en multiples *condiciones*
"""

numero=int(input("ingresa un numero: "))
if numero < 0:
    print('el numero es negativo')
elif numero > 0:
    print('el numero es positivo')
else:
    print('el numero es igual a cero')

"""# Anidacion"""

numero=int(input('ingrese un numero: '))
if numero > 0:
  if numero %2 == 0:
     print('el numero es par')
  else:
     print('el numero es impar')

elif numero == 0:
     print('el numero es cero')

else:
     print('el numero es negativo')

"""# Condicionales y operadores logicos"""

numero=int(input("ingrese un numero: "))
if numero > 0 and numero % 2 == 0: 
        print('el numero es entero y par')

elif numero > 0 and numero  % 2 != 0:
        print('el numero es negativo e impar')

elif numero == 0:
        print('el numero es cero')
else:
     print('el numero es negativo')

"""or"""

user = 'alecs'
access_level = 4
if user == 'admin' or access_level >= 4: #!!
          print('!Acceso concedido!')
else:
     print('!Acceso denegado!')

user = 'alecs'
access_level = 3
if user == 'admin' or access_level >= 4: #!!
          print('!Acceso concedido!')
else:
     print('!Acceso denegado!')