# -*- coding: utf-8 -*-
"""09_bucles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARmBZbZKnWzAdxUjMcWdgGlSxnhDhJsk

# Bucles/Loops/Ciclos

# While

Se utiliza para ejecutar un bloque de declaraciones repetidamente hasta que se cumpla una condición. Cuando la condición se vuelve falsa, las líneas de código después del ciclo continuarán ejecutándose.

**ejemplo**
"""

count = 0
while count < 5:
  print(count)
  count +=1
  #imprime del 0 al 4

"""En el ciclo while anterior, la condición se vuelve falsa cuando el conteo es 5. Ahí es cuando el ciclo se detiene. Si estamos interesados ​​en ejecutar un bloque de código una vez que la condición ya no sea cierta, podemos usar else."""

count = 0
while count < 5:
    print(count)
    count = count + 1
else:
    print(count)

"""La condición del ciclo anterior será falsa cuando el conteo sea 5 y el ciclo se detenga y la ejecución inicie la instrucción else. Como resultado se imprimirá 5.

**Break and Continue - Parte 1**

Break: Usamos break cuando queremos salir o detener el bucle.
"""

count = 0
while count < 5:
    print(count)
    count = count + 1
    if count == 3:
        break
        #El ciclo while anterior solo imprime 0, 1, 2, pero cuando llega a 3 se detiene.

"""Continue: la instrucción continue podemos omitir la iteración actual y continuar con la siguiente:"""

count = 0
while count < 5:
    if count == 3:
        continue
    print(count)
    count = count + 1
    break

    #El bucle while anterior solo imprime 0, 1 y 2 (se salta 3)
    #por otro lado el break termina el bucle

"""# For
La palabra **For** se usa para hacer un bucle, su funcion es similar a otros lenguajes de programación, pero con algunas diferencias de sintaxis. Loop se usa para iterar sobre una secuencia (es decir, listas, tuplas, diccionarios, cadenas.etc).
"""

#sintaxis
for iterator in lst:
  aqui va el codigo

"""**Ejemplo:**"""

numeros = [0,1,2,3,4,5]
for contador in numeros: #numeros es un nombre temporal para referirse a la lista , valido solo dentro del bucle
  print(contador) # el contador sera imprimido linea por linea, del 0 hasta el 5

"""# Ciclo for con cadena

"""

# syntax
for iterator in string:
    el código va aqui

languaje = 'python'
#for letter in languaje:
    #print(letter)

for i in range(len(languaje)):
   print(languaje[i])
   #de este modo se imprime letraa por letra

"""# Bucle for con diccionario
Hacer un bucle a través de un diccionario le da la clave del diccionario.
"""

person = {
    'name':'Erick',
    'last_name':'Borges',
    'age':23,
    'skills':['JavaScript', 'React', 'Swift', 'Python'],
    'address': {
        'street':'Fco. I. Madero',
        'telefono':782123456
    }
}

#for key in person:
   # print(key)

for key, value in person.items():
    print(' \'key\' :',key,' value:\' ', value)