# -*- coding: utf-8 -*-
"""12_modulos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfYQngPDwnz-MlH_D0lO8IE55lEqx4Lb

# Modulos
un modulo es un archivo que contiene un cojunto de codigos o un conjunto de funciones que pueden ser incluidos en nuestros proyectos

# Creación de un módulo
Para crear un módulo, escribimos nuestros códigos en un script de python y lo guardamos como un archivo .py
"""

import example
print(example.adicion(1,2))

"""# importando un modulo"""

#Modulo para trabajar con operaciones matematicas
import math
print(math.pi)
print(math.sqrt(16))
print(math.pow(2,3))
print(math.floor(9.84))

#podemos importar funciones especificas de cada modulo
from math import pi, sqrt, pow
print(pi)
print(sqrt(16))
print(pow(2,3))
print(math.floor(9.84))

#tambien podemos importar todas las funciones de golpe
from math import *
print(pi)
print(sqrt(16))
print(pow(2,3))
print(math.floor(9.84))

#tambien podemos renombrar una funcion
from math import pi as numPI
print(numPI)

"""# instalar modulos externos"""

#usamos el gestor de paquetes de python llamado pip
!pip install openai

import openai

openai.api_key = ""

while True:
    prompt = input("Introduce una pregunta: ")

    if prompt == 'exit':
        break

    completion = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.5,
    )

    print(completion.choices[0].text)